### ISSUE TITLE
Dockerize everything

### ISSUE THREAD

**Issue by ankitr** [ProjectCopilot/deployee#1]
Right now, we have a homemade solution with deploy scripts and tmux which is just waiting to become non-portable. We need to set up Docker on the server and our dev machines, and run all of our components through docker.

**Comment by gmittal** [comment]
What's the status on this? @ankitr

**Comment by ankitr** [comment]
The Docker components have been tested and seem to work ok. Now waiting on the deployment, which should come along with #13.
