### ISSUE TITLE
Automatically minify all static resources

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/deployee#14]
Minify `html`, `css`, and `js` files for faster load times in production.

**Comment by ankitr** [comment]
This shouldn't be on the deployee end, but instead done at build on each of the components. Have you ever worked with build systems in node, such as Grunt?

**Comment by gmittal** [comment]
No, not really. I've read up some stuff on Grunt, but never actually built anything with it. Will look into implementing that. 

For now, couldn't we just use a standard open source command line tool to minify our static resources?

**Comment by ankitr** [comment]
It still should be integrated in either the build or deploy scripts on the component level in the spirit of abstraction. I'll look into implementing it.
